# This workflow triggers beta releases

name: Beta release

run-name: "Beta release '${{ inputs.git-ref }}' (version: 2.0.0-beta.${{ inputs.patch }}, publish: ${{ inputs.publish || github.event_name == 'schedule' }})"

on:
  workflow_dispatch:
    inputs:
      git-ref:
        required: true
        type: string
        description: "The github ref of this beta version (i.e. main, 1234567)"
        default: main
      patch:
        required: true
        type: string
        description: "The patch of this beta version (i.e. 1, 2)"
      publish:
        required: false
        type: boolean
        default: false
        description: "Publish the beta release"

defaults:
  run:
    shell: bash

permissions:
  contents: write

jobs:
  release:
    name: Prepare beta release
    uses: ./.github/workflows/reusable_publish_version.yml
    with:
      environment: beta
      extra-features: storage-surrealkv,ml
      git-ref: ${{ inputs.git-ref }}
      patch: ${{ inputs.patch }}
      publish: ${{ inputs.publish }}
      create-release: ${{ inputs.publish }}
    secrets: inherit
